name: tools_of_worship_server
description: A server app using the shelf package and Docker.
version: 1.0.0
homepage: https://www.ToolsOfWorship.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  args: ^2.0.0
  mongo_dart: ^0.7.4
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  shelf_hotreload: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
