name: tools_of_worship_server
description: A server app using the shelf package.
version: 1.0.0
homepage: https://www.ToolsOfWorship.com
repository: https://github.com/FillipMatthew/ToolsOfWorship

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  tools_of_worship_api:
    path: ../tools_of_worship_api

  args: ^2.3.1
  mongo_dart: ^0.9.1
  shelf: ^1.3.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  shelf_hotreload: ^1.1.0

dev_dependencies:
  lints: ^2.0.1
  test_process: ^2.0.2
  test: ^1.20.0
  build_runner: ^2.3.3
  build_web_compilers: ^4.0.3
