name: tools_of_worship_server
description: A server app using the shelf package and Docker.
version: 1.0.0
homepage: https://www.ToolsOfWorship.com

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  args: ^2.3.1
  mongo_dart: ^0.8.0
  shelf: ^1.3.0
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  shelf_hotreload: ^1.1.0
  dart_jsonwebtoken: ^2.4.2
  xid: ^1.0.7
  crypto: ^3.0.2
  encrypt: ^5.0.1
  string_validator: ^0.3.0

dev_dependencies:
  lints: ^2.0.1
  test_process: ^2.0.2
  test: ^1.20.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
