name: tools_of_worship_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.ToolsOfWorship.com
repository: https://github.com/FillipMatthew/ToolsOfWorship

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # Client dependencies
  http: ^0.13.5
  google_sign_in: ^6.0.1

  # Server dependencies
  xid: ^1.0.7
  shelf: ^1.3.0
  shelf_router: ^1.1.3
  dart_jsonwebtoken: ^2.4.2
  basic_utils: ^5.5.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  string_validator: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
